// rename to: config.properties
trias.url=https://www.efa-bw.de/trias
trias.key=xxx
# Stuttgart Hbf, Stuttgart-Vaihingen, Bad Cannstatt, Zuffenhausen, (Böblingen)
trias.radares=de:08111:6118, de:08111:6002, de:08111:6333, de:08111:6294